# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install ZIP
        run: sudo apt-get install zip

      - name: Get Version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create ZIP
        run: zip -r QuickEntityEditorPieMod-$VERSION.zip . -x '*.git*' -x '*_H3_Retail_mods/LogPins.pdb'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: QuickEntityEditorPieMod-${{ env.VERSION }}.zip
